#!/usr/bin/env perl

use strict;
use warnings;

#use utf8::all;

use Encode qw( decode );
use Cpanel::JSON::XS;

my %env = map { $_ => decode( 'UTF-8', $ENV{$_} ) } keys %ENV;

print "Content-type: application/json; charset=UTF-8\n\n";
print Cpanel::JSON::XS->new->utf8->ascii->pretty->encode( \%env );

