requires 'Apache::Test';
requires 'Apache::TestRequest';
requires 'CGI';
requires 'Data::Printer';
requires 'Data::Validate::IP';
requires 'Encode';
requires 'File::Slurp';
requires 'Hash::Flatten';
requires 'JSON::XS';
requires 'List::AllUtils', '0.07';
requires 'List::Util', '>= 1.38';
requires 'Net::Works::Network';
